from selenium.webdriver.common.by import By

class LoginPageLocators(object):
  USERNAME      = (By.NAME, 'username')
  PASSWORD      = (By.NAME, 'password')
  SUBMIT_BUTTON = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/div/div/div[2]/form/fieldset/span/input')
  LANGUAGE_PICKER       = (By.ID, 'language')
  TYPE_SELECTOR = (By.XPATH, '//*[@id="type"]')
  DISPATCHER_TYPE = (By.XPATH, '//*[@id="type"]/option[2]')
  USERNAME_DROPDOWN = (By.XPATH, '//*[@id="operr-nav-wrapper nav_div"]/nav/div/div[4]/div[3]/ul/li[2]/ul/li/a')
  LOGIN_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/div/div/div[2]/form/fieldset/span/input')
  chat_page = (By.XPATH, '/html/body/div[1]/aside[2]/div/section/ul/li[24]/a')

class DashboardPageLocators(object):
  HEADER = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/h1/span')
  ANALYSIS_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[1]/a')
  STATISTIC_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[2]/a')
  MONTH_3 = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/div[1]/div[1]/button[1]')
  MONTH_6 = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/div[1]/div[1]/button[2]')
  MONTH_12 = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/div[1]/div[1]/button[3]')
  AREA_CHART = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/div[1]/div[2]/div[1]/span')
  PIE_CHART = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/div[1]/div[3]/div[1]/span')
  PERC_COLU_CHART = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/div[1]/div[4]/div[1]/span')
  AUTO_REFRESH_BTN = (By.XPATH, '//*[@id="button-content"]/button[1]/span')
  STOP_AUTO_REFRESH_BTN = (By.XPATH, '//*[@id="button-content"]/button[2]/span')
  MANUAL_REFRESH_BTN = (By.XPATH, '//*[@id="button-content"]/button[3]/span')
  HEAT_MAP_BTN = (By.XPATH, '//*[@id="button-content"]/button[4]/span')
  TRIPS_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/div[2]/div[1]/div[3]')
  DRIVERS_ON_OFF_DUTY = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/div[2]/div[1]/div[4]')

class NavigationPageLocators(object):
  BILLING_TAB = (By.XPATH, '/html/body/div[1]/aside[2]/div/section/ul/li[18]/a/span')
  NAVIGATION_BUTTON = (By.XPATH, '//*[@id="operr-header-left-collapse-button"]/a')
  PAYMENT_TAB = (By.XPATH,'/html/body/div[1]/aside[2]/div/section/ul/li[19]/a/span')
  ADMIN_TAB = (By.XPATH, '/html/body/div[1]/aside[2]/div/section/ul/li[3]/a')
  INACTIVE_DRIVER_TAB = (By.XPATH, '/html/body/div[1]/aside[2]/div/section/ul/li[4]/a/span')
  ADMINGROUP_TAB = (By.XPATH,'/html/body/div[1]/aside[2]/div/section/ul/li[5]/a/span')
  ACTIVE_TAB = (By.XPATH, '/html/body/div[1]/aside[2]/div/section/ul/li[6]/a/span')
  COMPANY_TAB = (By.XPATH, '/html/body/div[1]/aside[2]/div/section/ul/li[10]/a/span')
  VEHICLES_TAB = (By.XPATH,'/html/body/div[1]/aside[2]/div/section/ul/li[7]/a/span')
  RATEBOOK_TAB = (By.XPATH,'/html/body/div[1]/aside[2]/div/section/ul/li[9]/a')
  AGENCY_TAB = (By.XPATH,'/html/body/div[1]/aside[2]/div/section/ul/li[12]/a')
  BASE_TAB = (By.XPATH, '/html/body/div[1]/aside[2]/div/section/ul/li[11]/a')
  DISPATCHING_TAB = (By.XPATH, '/html/body/div[1]/aside[2]/div/section/ul/li[14]/a/span')
  CONTENT_TAB = (By.XPATH, '/html/body/div[1]/aside[2]/div/section/ul/li[20]/a/span')
  FLIGHT_CHECK = (By.XPATH, '/html/body/div[1]/aside[2]/div/section/ul/li[22]/a/span')
  ADMIN_DROPDOWN = (By.XPATH, '//*[@id="operr-nav-wrapper nav_div"]/nav/div/div[4]/div[3]/ul/li[2]')
  DASHBOARD_TAB = (By.XPATH, '/html/body/div[1]/aside[2]/div/section/ul/li[2]/a/span')

class BillingPageLocators(object):
  COMPANYINFO_DROPDOWN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/billing-tab-data-table/div/div[1]/form/div[1]/select')
  DRIVER_INFO = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/billing-tab-data-table/div/div[1]/form/div[3]/select')
  AGENCYNAME_DROPDOWN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/billing-tab-data-table/div/div[1]/form/div[2]/select')
  CALENDAR_DROPDOWN = (By.XPATH,'//*[@id="reportrange"]/span')
  BASEINFO_DROPDOWN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/billing-tab-data-table/div/div[1]/form/div[2]/select')
  TODAY_BUTTON = (By.XPATH,'/html/body/div[3]/div[3]/ul/li[1]')
  YESTERDAY_BUTTON = (By.XPATH, '/html/body/div[3]/div[3]/ul/li[2]')
  LAST7DAYS_BUTTON = (By.XPATH, '/html/body/div[3]/div[3]/ul/li[3]')
  LAST30DAYS_BUTTON = (By.XPATH,'/html/body/div[3]/div[3]/ul/li[4]')
  THISMONTH_BUTTON = (By.XPATH,'/html/body/div[3]/div[3]/ul/li[5]')
  LASTMONTH_BUTTON  = (By.XPATH,'/html/body/div[3]/div[3]/ul/li[6]')
  CANCEL_SEARCH =(By.XPATH,'/html/body/div[13]/div[3]/div/button[2]')
  RESULT_BAR = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/billing-tab-data-table/div/div[2]/div[1]/div[1]/label')

class AdminPageLocators(object):
  SHOW_ALL_ADMIN_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[1]/a/uib-tab-heading/span')
  ADD_NEW_ADMIN_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[2]/a/uib-tab-heading/span')
  ADMIN_MENU_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[3]/a/uib-tab-heading/span')
  SEARCHING_TYPE_DROPDOWN = (By.XPATH, '//*[@id="admin-table-searching-column-name-selection"]')
  SEARCHING_BOX = (By.XPATH, '//*[@id="admin-table-search"]')
  SEARCHING_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/admin-tab-data-table/div/div[1]/div[4]/button')
  SHOW_ENTRIES_OPTION = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/admin-tab-data-table/div/div[1]/div[1]/label/select')
  TABLE_STATUS = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Status")])[1]')
  TABLE_USERNAME = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "User name")])[1]')
  TABLE_EMAIL =(By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Email")])[1]')
  TABLE_PHONE = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Phone")])[1]')
  TABLE_2ND_PHONE = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Secondary Phone")])[1]')
  TABLE_ADMIN_LVL = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Admin Level")])[1]')
  TABLE_COMPANY = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Company")])[1]')
  TABLE_BASE = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Base")])[1]')
  TABLE_ADDRESS = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Address")])[1]')
  TABLE_NAME = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Name")])[1]')
  SEARCHING_TEXT = (By.XPATH, '//*[@id="DataTables_Table_5"]/tbody/tr[1]/td[3]')
  FIRST_NAME_BOX = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[2]/input')
  LAST_NAME_BOX = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[3]/input')
  USERNAME_BOX = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[4]/input')
  EMAIL_BOX = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[5]/input')
  PASSWORD_BOX = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[6]/input')
  PHONE_BOX_ADD = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[7]/input')
  PHONE_BOX_EDIT = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[6]/input')
  PERMISSION_LVL_DROPDOWN_ADD = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[9]/select')
  PERMISSION_LVL_DROPDOWN_EDIT = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[8]/select')
  COMPANY_DROPDOWN_EDIT = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[9]/select')
  COMPANY_DROPDOWN_ADD = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[10]/select')
  BASE_DROPDOWN_EDIT = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[10]/select')
  BASE_DROPDOWN_ADD = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[11]/select')
  STATUS_ACTIVE = (By.XPATH, '//*[@id="status_r1"]')
  STATUS_INACTIVE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[3]/label[3]/span')
  ADMIN_PHOTO_UPLOAD = (By.XPATH, '//*[@id="E6YkV"]')
  SUBMIT_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[3]/span/button/span')
  ACTION_BTN_1ST_USER = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//td[@class="table-cell-center"]//i)[2]')
  SUBMIT_EDIT_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[3]/span/button')

class InactiveDriverLocators(object):
  SEARCHING_BOX = (By.XPATH, '//*[@id="admin-table-search"]')
  SEARCHING_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/driver-tab-data-table/div/div[1]/div[4]/a')
  TABLE_ID = (By.XPATH, '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "ID")]')
  TABLE_FLEET_NUMBER = (By.XPATH, '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Fleet")]')
  TABLE_STATUS = (By.XPATH, '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Status")]')
  TABLE_NAME = (By.XPATH, '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Name")]')
  TABLE_USERNAME = (By.XPATH, '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "User name")]')
  TABLE_EMAIL = (By.XPATH, '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Email")]')
  TABLE_PHONE = (By.XPATH, '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Phone")]')
  TABLE_VEHICLE_ID = (By.XPATH, '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Vehicle ID")]')
  TABLE_BASE = (By.XPATH, '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Base")]')
  TABLE_DUTY_STATUS = (By.XPATH, '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Duty Status")]')
  TABLE_CREATED_DATE = (By.XPATH, '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Created Date")]')
  ACTION_EDIT_1ST_USER = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//td/i)[3]')
  EDIT_FLEET_NUMBER = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[2]/input')
  EDIT_FIRST_NAME = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[3]/input')
  EDIT_LAST_NAME = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[4]/input')
  EDIT_USERNAME = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[5]/input')
  EDIT_SUBMIT_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[5]/span/button')
  EDIT_EMAIL = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[6]/input')
  EDIT_PHONE_NUMBER = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[8]/input')
  EDIT_DATE_OF_BIRTH = (By.XPATH, '//*[@id="birth-day"]')
  EDIT_GENDER = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[11]/select')
  EDIT_COUNTRY_OF_ORIGIN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[12]/select')
  EDIT_DRIVING_EXP = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[13]/input')
  EDIT_DRIVER_TYPE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[14]/select')
  EDIT_AFFILI_COMPANY_NAME = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[2]/div[2]/select')
  EDIT_AFFILI_BASE_NAME = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[2]/div[3]/select')
  BASE_APPROVED_ACTIVE = (By.XPATH, '//*[@id="status_r1"]')
  BASE_APPROVED_INACTIVE = (By.XPATH, '//*[@id="status_r2"]')
  OPERR_STATUS_APPROVE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[2]/div[9]/button[1]')
  OPERR_STATUS_DISAPPROVE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[2]/div[9]/button[2]')
  EDIT_DRIVER_LICENSE_NUMBER = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[2]/div[1]/input')
  EDIT_DRIVER_LICENSE_CLASS = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[2]/div[2]/input')
  EDIT_DRIVER_LICENSE_STATE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[2]/div[3]/select')
  EDIT_DRIVER_LICENSE_START_DATE = (By.XPATH, '//*[@id="driver-license-date"]/div[1]/input')
  EDIT_DRIVER_LICENSE_EXP_DATE = (By.XPATH, '//*[@id="driver-license-date"]/div[2]/input')
  EDIT_DRIVER_TLC_FHV_NUMBER = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[3]/div[1]/input')
  EDIT_TLC_FHV_START_DATE = (By.XPATH, '//*[@id="driver_tlc_fhv_license-date"]/div[1]/input')
  EDIT_TLC_FHV_EXP_DATE = (By.XPATH, '//*[@id="driver_tlc_fhv_license-date"]/div[2]/input')
  EDIT_BACKGROUND_CHECK_START_DATE =  (By.XPATH, '//*[@id="background-check-date"]/div[1]/input')
  EDIT_BACKGROUND_CHECK_EXP_DATE = (By.XPATH, '//*[@id="background-check-date"]/div[2]/input')
  EDIT_DRIVING_RECORD_START_DATE = (By.XPATH, '//*[@id="driving-record-date"]/div[1]/input')
  EDIT_DRIVING_RECORD_EXP_DATE = (By.XPATH, '//*[@id="driving-record-date"]/div[2]/input')
  EDIT_DRUG_SCREEN_START_DATE = (By.XPATH, '//*[@id="drug-screen-date"]/div[1]/input')
  EDIT_DRUG_SCREEN_EXP_DATE = (By.XPATH, '//*[@id="drug-screen-date"]/div[2]/input')
  EDIT_VEHICLE_INFO_DROPDOWN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[4]/div[2]/div[2]/select')
  EDIT_CROSS_COUNTY_BOTH_BTN = (By.XPATH, '//*[@id="cross_county_r3"]')


class ActiveDriverLocators(object):
    SEARCHING_BOX = (By.XPATH, '//*[@id="admin-table-search"]')
    SEARCHING_BTN = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/driver-tab-data-table/div/div[1]/div[4]/a')
    TABLE_ID = (By.XPATH,
                '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "ID")]')
    TABLE_FLEET_NUMBER = (By.XPATH,
                          '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Fleet")]')
    TABLE_STATUS = (By.XPATH,
                    '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Status")]')
    TABLE_NAME = (By.XPATH,
                  '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Name")]')
    TABLE_USERNAME = (By.XPATH,
                      '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "User name")]')
    TABLE_EMAIL = (By.XPATH,
                   '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Email")]')
    TABLE_PHONE = (By.XPATH,
                   '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Phone")]')
    TABLE_VEHICLE_ID = (By.XPATH,
                        '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Vehicle ID")]')
    TABLE_BASE = (By.XPATH,
                  '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Base")]')
    TABLE_DUTY_STATUS = (By.XPATH,
                         '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Duty Status")]')
    TABLE_CREATED_DATE = (By.XPATH,
                          '//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Created Date")]')
    ACTION_EDIT_1ST_USER = (
    By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//td/i)[3]')
    EDIT_FLEET_NUMBER = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[2]/input')
    EDIT_FIRST_NAME = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[3]/input')
    EDIT_LAST_NAME = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[4]/input')
    EDIT_USERNAME = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[5]/input')
    EDIT_SUBMIT_BTN = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[5]/span/button')
    EDIT_EMAIL = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[6]/input')
    EDIT_PHONE_NUMBER = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[8]/input')
    EDIT_DATE_OF_BIRTH = (By.XPATH, '//*[@id="birth-day"]')
    EDIT_GENDER = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[11]/select')
    EDIT_COUNTRY_OF_ORIGIN = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[12]/select')
    EDIT_DRIVING_EXP = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[13]/input')
    EDIT_DRIVER_TYPE = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[14]/select')
    EDIT_AFFILI_COMPANY_NAME = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[2]/div[2]/select')
    EDIT_AFFILI_BASE_NAME = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[2]/div[3]/select')
    EDIT_DRIVER_LICENSE_NUMBER = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[2]/div[1]/input')
    EDIT_DRIVER_LICENSE_CLASS = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[2]/div[2]/input')
    EDIT_DRIVER_LICENSE_STATE = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[2]/div[3]/select')
    EDIT_DRIVER_LICENSE_START_DATE = (By.XPATH, '//*[@id="driver-license-date"]/div[1]/input')
    EDIT_DRIVER_LICENSE_EXP_DATE = (By.XPATH, '//*[@id="driver-license-date"]/div[2]/input')
    EDIT_DRIVER_TLC_FHV_NUMBER = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[3]/div[1]/input')
    EDIT_TLC_FHV_START_DATE = (By.XPATH, '//*[@id="driver_tlc_fhv_license-date"]/div[1]/input')
    EDIT_TLC_FHV_EXP_DATE = (By.XPATH, '//*[@id="driver_tlc_fhv_license-date"]/div[2]/input')
    EDIT_BACKGROUND_CHECK_START_DATE = (By.XPATH, '//*[@id="background-check-date"]/div[1]/input')
    EDIT_BACKGROUND_CHECK_EXP_DATE = (By.XPATH, '//*[@id="background-check-date"]/div[2]/input')
    EDIT_DRIVING_RECORD_START_DATE = (By.XPATH, '//*[@id="driving-record-date"]/div[1]/input')
    EDIT_DRIVING_RECORD_EXP_DATE = (By.XPATH, '//*[@id="driving-record-date"]/div[2]/input')
    EDIT_DRUG_SCREEN_START_DATE = (By.XPATH, '//*[@id="drug-screen-date"]/div[1]/input')
    EDIT_DRUG_SCREEN_EXP_DATE = (By.XPATH, '//*[@id="drug-screen-date"]/div[2]/input')
    EDIT_VEHICLE_INFO_DROPDOWN = (
    By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[4]/div[2]/div[2]/select')
    EDIT_CROSS_COUNTY_BOTH_BTN = (By.XPATH, '//*[@id="cross_county_r3"]')
    EDIT_DSP_PERCENT = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[2]/div[6]/div[1]/input')
    EDIT_BASE_PERCENT = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[2]/div[6]/div[2]/input')
    EDIT_DRIVER_PERCENT = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[2]/div[6]/div[3]/input')
    EDIT_RESERVE_PERCENT = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[2]/div[6]/div[4]/input')
    BASE_APPROVED_ACTIVE_BTN = (By.XPATH, '//*[@id="status_r1"]')
    ADD_NEW_DRIVER_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[2]/a/uib-tab-heading/span')
    EDIT_PASSWORD = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[1]/div[7]/input')


class PaymentPageLocators(object):
  COMPANYINFO_DROPDOWN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/payment-tab-data-table/div/div[1]/form/div[1]/select')
  DRIVER_INFO = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/payment-tab-data-table/div/div[1]/form/div[3]/select')
  AGENCYNAME_DROPDOWN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/payment-tab-data-table/div/div[1]/form/div[4]/select')
  CALENDAR_DROPDOWN = (By.XPATH, '//*[@id="reportrange"]/span')
  BASEINFO_DROPDOWN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/payment-tab-data-table/div/div[1]/form/div[2]/select')
  SUBMIT_BUTTON = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/payment-tab-data-table/div/div[1]/form/div[7]/span/button/span')
  CANCEL_SEARCH = (By.XPATH, '/html/body/div[3]/div[3]/div/button[2]')
  RESULT_BAR = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/payment-tab-data-table/div/div[2]/button[1]/span')
  TODAY_BUTTON = (By.XPATH,'/html/body/div[3]/div[3]/ul/li[1]')
  EXPORTDETAIL_BUTTON = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/payment-tab-data-table/div/div[2]/button[1]/span')
  EXPORTSUMMARY_BUTTON=(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/payment-tab-data-table/div/div[2]/button[2]/span')
  APPROVE_BUTTON=(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/payment-tab-data-table/div/div[2]/button[3]/span')
  
class AdminGroupLocators(object):
    SHOW_ALL_ADMIN_GROUP_TAB=(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[1]')
    ADD_A_NEW_GROUP_TAB = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[2]')
    SHOW_ENTRIES_DROPDOWN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/group-tab-data-table/div/div[1]/div/label/select')
    ACTION_EDIT_BUTTON = (By.XPATH,'//td[@class="table-cell-center"][1]/i')
    ADMIN_INFORMATION_BANNER =(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[1]/span')
    ADMIN_DETAILED_INFO_BANNER = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[1]/span')
    USERNAME_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[2]/input')
    EMAIL_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[3]/input')
    PHONE_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[4]/input')
    ADDRESS_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[5]/input')
    ACTIVE_POINTER = (By.XPATH,'//*[@id="status_r1"]')
    INACTIVE_POINTER = (By.XPATH,'//*[@id="status_r2"]')
    SUBMIT_BUTTON = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[3]/span/button/span')
    PHONE_FIRST=(By.XPATH,'//*[@id="DataTables_Table_1"]/tbody/tr[1]/td[3]')
    ADDRESS_FIRST=(By.XPATH,'//*[@id="DataTables_Table_1"]/tbody/tr[1]/td[4]')
    SHOW_ADMIN = (By.XPATH,'(//td[@class="table-cell-center"] /i)[2]')
    USERNAME_ADD = (By.XPATH,'/html/body/div[1]/div/div/div[2]/table/tbody/tr[1]/th[1]/span')
    ADD_ADMIN_TO_GROUP = (By.XPATH,'/html/body/div[1]/div/div/div[2]/div/button')
    CHECK_ADMIN = (By.XPATH,'/html/body/div[1]/div/div/div[2]/table/tbody/tr[2]/td[1]/input')
    ADDED_ADMIN_NAME = (By.XPATH,'/html/body/div[1]/div/div/div[2]/table/tbody/tr[2]/td[2]')
    
class UserLocators(object):
    OPERR_USERS_VIEW_ALL_BANNER = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/h1/span[1]')
    SHOW_ALL_USERS=(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/h1/span[1]')
    ADD_A_NEW_USER_BTN = (By.XPATH,'//*[contains(text(), "Add A New User")]')
    USERNAME_COLUMN = (By.XPATH,'//*[contains(text(), "User name")]')
    ACTIVE_LABLE = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/user-tab-data-table/div/div[1]/div[2]/label')
    SHOW_ENTRIES_DROPDOWN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/user-tab-data-table/div/div[1]/div[1]/label/select')
    SEARCHING_COLUMN_DROPDOWN = (By.XPATH,'//*[@id="admin-table-searching-column-name-selection"]')
    SEARCHING_TEXTBOX = (By.XPATH,'//*[@id="admin-table-search"]')
    SEARCH_BTN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/user-tab-data-table/div/div[1]/div[4]/button')
    ACTION_BTN = (By.XPATH,'(//td[@class="table-cell-center"]/i)[2]')
    USERNAME_TEXTBOX=(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form[2]/div[1]/div[2]/div[1]/input')
    EMAIL_TEXTBOX =(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form[2]/div[1]/div[2]/div[2]/input')
    PSW_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form[2]/div[1]/div[2]/div[3]/input')
    FN_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form[2]/div[1]/div[2]/div[4]/input')
    LN_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form[2]/div[1]/div[2]/div[5]/input')
    PHONE_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form[2]/div[1]/div[3]/div[1]/input')
    ADDRESS_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form[2]/div[1]/div[3]/div[3]/input')
    USERNAME_TEXTBOX_EDIT = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[2]/div[1]/input')
    EMAIL_TEXTBOX_EDIT = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[2]/div[2]/input')
    FN_TEXTBOX_EDIT = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[2]/div[4]/input')
    LN_TEXTBOX_EDIT = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[2]/div[5]/input')
    PHONE_TEXTBOX_EDIT = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[3]/div[1]/input')
    ADDRESS_TEXTBOX_EDIT = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[3]/div[3]/input')
    STATUS_POINTER = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form[2]/div[1]/div[3]/div[5]/input[1]')
    SUBMIT_BTN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form[2]/div[3]/span/button')


class CompanyLocators(object):
    SHOW_ALL_COMPANY_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[1]/a/uib-tab-heading/span')
    ADD_A_NEW_COMPANY_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[2]/a/uib-tab-heading/span')
    SEARCHING_BOX = (By.XPATH, '//*[@id="admin-table-search"]')
    SEARCHING_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/company-tab-data-table/div/div[1]/div[4]/button')
    TABLE_STATUS = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Status")])[1]')
    TABLE_COMPANY = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Company")])[1]')
    ACTION_FOR_1ST_COMPANY = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//td/i)[2]')
    EDIT_COMPANY_NAME = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[1]/input')
    MON = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[2]/label[2]/input')
    TUE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[2]/label[3]/input')
    WED = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[2]/label[4]/input')
    THU = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[2]/label[5]/input')
    FRI = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[2]/label[6]/input')
    SAT = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[2]/label[7]/input')
    SUN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[2]/label[8]/input')
    WORKTIME_START_HOUR = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[3]/div/table/tbody/tr[2]/td[1]/input')
    WORKTIME_START_MIN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[3]/div/table/tbody/tr[2]/td[3]/input')
    WORKTIME_END_HOUR = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[4]/div/table/tbody/tr[2]/td[1]/input')
    WORKTIME_END_MIN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[4]/div/table/tbody/tr[2]/td[3]/input')
    EDIT_PHONE_NUMBER = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[5]/input')
    EDIT_EMAIL = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[6]/input')
    EDIT_ADDRESS = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[1]/input')
    EDIT_STATE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[3]/select')
    EDIT_CITY = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[4]/input')
    EDIT_ZIPCODE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[5]/input')
    ACTIVE_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[6]/input[1]')
    INACVTIVE_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[6]/input[2]')
    SUBMIT_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[3]/span/button')
    SEARCHING_DROPDOWN = (By.XPATH, '//*[@id="admin-table-searching-column-name-selection"]')
    SEARCHING_DROPDOWN_COMPANY = (By.XPATH, '//*[@id="admin-table-searching-column-name-selection"]/option[2]')


class VehiclePageLocators(object):
    VEHICLE_VIEW_ALL_BANNER = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/h1/span')
    SHOW_ALL_VEHICLES_TAB = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[1]/a')
    ADD_A_NEW_VEHICLE_TAB = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[2]/a')
    SHOW_ALL_ENTIRES_DROPDOWN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/vehicle-tab-data-table/div/div[1]/div[1]/label/select')
    NUMBER_OF_ACTIVE_LABLE = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/vehicle-tab-data-table/div/div[1]/div[2]/label')
    SEARCHING_COLUMN = (By.XPATH,'//*[@id="admin-table-searching-column-name-selection"]')
    SEARCHING_TEXTBOX_DROPDOWN = (By.XPATH,'//*[@id="admin-table-search"]')
    SEARCHING_BUTTON = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/vehicle-tab-data-table/div/div[1]/div[4]/button')
    EDIT_BUTTON = (By.XPATH,'(//td[@class="table-cell-center"]/i)[2]')
    VIN_COLUMN = (By.XPATH,'// table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(),"VIN")]')
    PLATE_NUMBER_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[2]/div[1]/input')
    AFFILIATED_BASE_NAME_DROPDOWN= (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[1]/div[3]/div[2]/select')
    SUBMIT_BTN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[4]/span/button')
    LIABILITY_AMOUNT=(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[3]/div[2]/div[1]/input')


class RateBookLocators(object):
    RATEBOOK_BANNER = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/h1/span')
    SHOW_ALL_RATEBOOKS = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[1]/a')
    ADD_A_NEW_RATEBOOK = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[2]/a')
    BASE_NAME_COLUMN = (By.XPATH, '(//*[contains(text(),"Base Name")])[2]')
    SHOW_ENTRIES_DROPDOWN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/ratebook-tab-data-table/div/div[1]/div[1]/label/select')
    SEARCHING_COLUMN = (By.XPATH,'//*[@id="admin-table-searching-column-name-selection"]')
    SEARCHING_TEXTBOX = (By.XPATH,'//*[@id="admin-table-search"]')
    SEARCHING_BTN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/ratebook-tab-data-table/div/div[1]/div[3]/button')
    ACTION_BTN = (By.XPATH, '(//td[@class="table-cell-center"]/i)[2]')
    RATEBOOK_TYPE_DROPDOWN =(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/select')
    FARECALCULATION_TYPE_DROPDOWN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/select')
    COMPANY_DROPDOWN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[4]/div[1]/div[1]/select')
    PER_MIN_FARE_TEXTBOX =(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[4]/div[2]/div[1]/input')
    BASE_DROPDOWN=(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[4]/div[1]/div[2]/select')
    MINIMUM_FARE_TEXTBOX=(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[4]/div[2]/div[2]/input')
    CAR_TYPE_DROPDOWN=(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[4]/div[1]/div[3]/select')
    BASE_FARE_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[4]/div[1]/div[4]/input')
    CANCELLATION_FEE1= (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[4]/div[2]/div[3]/input')
    STATUS_POINTER = (By.XPATH,'//*[@id="status_r1"]')
    PER_MILE_FARE_TEXTBOX=(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[4]/div[1]/div[5]/input')
    CANCELLATION_FEE2=(By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[4]/div[2]/div[5]/input')
    SUBMIT_BUTTON = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[5]/span/button')

class AgencyLocators(object):
    OPERR_AGENCY_VIEW_ALL_BANNER = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/h1/span')
    SHOW_ALL_AGENCIES_TAB = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[1]/a')
    ADD_A_NEW_AGENCY_TAB = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[2]/a')
    SHOW_ENTRIES_DROPDOWN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/agency-tab-data-table/div/div[1]/div[1]/label')
    SEARCHING_COLUMN = (By.XPATH,'//*[@id="admin-table-searching-column-name-selection"]')
    SEARCHING_TEXTBOX = (By.XPATH,'//*[@id="admin-table-search"]')
    SEARCHING_BTN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/agency-tab-data-table/div/div[1]/div[4]/button')
    ACTIVE_LABLE = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/agency-tab-data-table/div/div[1]/div[4]/button')
    EDIT_BTN = (By.XPATH,'(//td[@class="table-cell-center"]/i)[2]')
    ID_COLUMN = (By.XPATH,'//th[@column-name="id"]')
    TYPE_DROPDOWN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[1]/select')
    NAME_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[2]/input')
    CODE_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[3]/input')
    ADDRESS_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[1]/input')
    STATE_DROPDOWN = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[3]/select')
    CITY_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[4]/input')
    ZIP_CODE = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[5]/input')
    MON_POINTER = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[4]/label[2]/input')
    TUE_POINTER = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[4]/label[3]/input')
    WED_POINTER = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[4]/label[4]/input')
    THU_POINTER = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[4]/label[5]/input')
    FRI_POINTER = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[4]/label[6]/input')
    SAT_POINTER = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[4]/label[7]/input')
    SUN_POINTER = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[4]/label[8]/input')
    START_HOUR =  (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[5]/div/table/tbody/tr[2]/td[1]/input')
    END_HOUR = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[6]/div/table/tbody/tr[2]/td[1]/input')
    PHONE_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[7]/input')
    EMAIL_TEXTBOX = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[8]/input')
    SUBMIT = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[3]/span/button/span')
    STATUS_ACTIVE_POINTER = (By.XPATH,'//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[8]/input[1]')


class BasePageLocators(object):
    SHOW_ALL_BASES = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[1]/a/uib-tab-heading/span')
    ADD_A_NEW_BASE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[2]/a/uib-tab-heading/span')
    SEARCHING_DROPDOWN = (By.XPATH, '//*[@id="admin-table-searching-column-name-selection"]')
    SEARCHING_DROPDOWN_BASENAME = (By.XPATH, '//*[@id="admin-table-searching-column-name-selection"]/option[2]')
    SEARCHING_DROPDOWN_BASETYPE = (By.XPATH, '//*[@id="admin-table-searching-column-name-selection"]/option[3]')
    SEARCHING_DROPDOWN_COMPANY = (By.XPATH, '//*[@id="admin-table-searching-column-name-selection"]/option[4]')
    SEARCHING_BOX = (By.XPATH, '//*[@id="admin-table-search"]')
    SEARCHING_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/base-tab-data-table/div/div[1]/div[4]/button')
    TABLE_STATUS = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Status")])[1]')
    TABLE_BASENAME = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Base Name")])[1]')
    TABLE_BASETYPE = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Base Type")])[1]')
    TABLE_COMPANY = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Company")])[1]')
    TABLE_FARE_TYPE =(By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Fare")])[1]')
    ACTION_FOR_1ST_BASE =(By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//td/i)[2]')
    EDIT_COMPANY_DROPDOWN =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[1]/div[1]/select')
    EDIT_BASENAME =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[1]/div[2]/input')
    EDIT_BASETYPE_DROPDOWN =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[1]/div[3]/select')
    EDIT_FARE_TYPE =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[1]/div[4]/select')
    EDIT_FEDERAL_TAX_ID =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[1]/div[5]/input')
    EDIT_ADDRESS =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[1]/div[6]/input')
    EDIT_STATE =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[1]/div[7]/select')
    EDIT_CITY =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[1]/div[8]/input')
    EDIT_ZIPCODE =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[1]/div[9]/input')
    EDIT_MAIN_CONTACT =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[2]/div[1]/input')
    EDIT_BUSINESS_PHONE =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[2]/div[2]/input')
    EDIT_BUSINESS_FAX =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[2]/div[3]/input')
    TRACKING_MODE_ACTIVE =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[2]/div[4]/input[1]')
    EDIT_TRACKING_MODE_INACTIVE =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[2]/div[4]/input[2]')
    EDIT_STATUS_ACTIVE =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[2]/div[5]/input[1]')
    EDIT_STATUS_INACTIVE =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[2]/div[2]/div[5]/input[2]')
    EDIT_BASE_TLC_LICENSE_NUMBER =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[4]/div/div[1]/input')
    EDIT_BASE_TLC_LICENSE_START_DATE =(By.XPATH, '//*[@id="TLC_license_start_end"]/div[1]/input')
    EDIT_BASE_TLC_LICENSE_EXP_DATE =(By.XPATH, '//*[@id="TLC_license_start_end"]/div[2]/input')
    EDIT_AUTOMOBILE_LIABILITY_AMOUNT =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[5]/div[1]/div[2]/input')
    EDIT_AUTO_OPERR_CERTIFICATE_HOLDER =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[5]/div[1]/div[3]/select')
    EDIT_AUTO_SELF_INSURED =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[5]/div[1]/div[4]/select')
    EDIT_AUTO_OPERR_ADDITIONAL_INSURED =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[5]/div[1]/div[5]/select')
    EDIT_AUTO_NAME_AFFORD_COVERAGE =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[5]/div[1]/div[6]/input')
    EDIT_AUTOMOBILE_INSURANCE_START_DATE =(By.XPATH, '//*[@id="auto_insurance_start_end"]/div[1]/input')
    EDIT_AUTOMOBILE_INSURANCE_EXP_DATE =(By.XPATH, '//*[@id="auto_insurance_start_end"]/div[2]/input')
    EDIT_GENERAL_LIABILITY_AMOUNT =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[5]/div[2]/div[2]/input')
    EDIT_GENERAL_OPERR_LIABILITY_AMOUNT =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[5]/div[2]/div[3]/select')
    EDIT_GENERAL_OPERR_CERTIFICATE_HOLDER = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[5]/div[2]/div[3]/select')
    EDIT_GENERAL_SELF_INSURED =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[5]/div[2]/div[4]/select')
    EDIT_GENERAL_OPERR_ADDITIONAL_INSURED =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[5]/div[2]/div[5]/select')
    EDIT_GENERAL_NAME_AFFORD_COVERAGE =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[5]/div[2]/div[6]/input')
    EDIT_GENERAL_INSURANCE_START_DATE =(By.XPATH, '//*[@id="gen_insurance_start_end"]/div[1]/input')
    EDIT_GENERAL_INSURANCE_EXP_DATE =(By.XPATH, '//*[@id="gen_insurance_start_end"]/div[2]/input')
    EDIT_IRS_NAME =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[6]/div[1]/div[2]/input')
    EDIT_TIN_EIN_SNN =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[6]/div[1]/div[3]/input')
    EDIT_FEDERAL_W9_START_DATE =(By.XPATH, '//*[@id="fed_start_end"]/div[1]/input')
    EDIT_FEDERAL_W9_EXP_DATE =(By.XPATH, '//*[@id="fed_start_end"]/div[2]/input')
    EDIT_WORKER_COMPENSATION_AMOUNT =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[6]/div[2]/div[2]/input')
    EDIT_WORKER_COMPENSATION_START_DATE =(By.XPATH, '//*[@id="worker_com_start_end"]/div[1]/input')
    EDIT_WORKER_COMPENSATION_EXP_DATE =(By.XPATH, '//*[@id="worker_com_start_end"]/div[2]/input')
    EDIT_TRAINING_ATT_START_DATE =(By.XPATH, '//*[@id="train_attest_start_end"]/div[1]/input')
    EDIT_TRAINING_ATT_EXP_DATE =(By.XPATH, '//*[@id="train_attest_start_end"]/div[2]/input')
    EDIT_SCHEDULE_A_START_DATE =(By.XPATH, '//*[@id="schedule_a_start_end"]/div[1]/input')
    EDIT_SCHEDULE_A_EXP_DATE =(By.XPATH, '//*[@id="schedule_a_start_end"]/div[2]/input')
    EDIT_SCHEDULE_B_START_DATE =(By.XPATH, '//*[@id="schedule_b_start_end"]/div[1]/input')
    EDIT_SCHEDULE_B_EXP_DATE =(By.XPATH, '//*[@id="schedule_b_start_end"]/div[2]/input')
    EDIT_AETNA_INSURANCE_START_DATE =(By.XPATH, '//*[@id="aetna_ins_amend_start_end"]/div[1]/input')
    EDIT_AETNA_INSURANCE_EXP_DATE =(By.XPATH, '//*[@id="aetna_ins_amend_start_end"]/div[2]/input')
    EDIT_INSURANCE_ENDORSEMENT_START_DATE =(By.XPATH, '//*[@id="ins_endor_amend_start_end"]/div[1]/input')
    EDIT_INSURANCE_ENDORSEMENT_EXP_DATE =(By.XPATH, '//*[@id="ins_endor_amend_start_end"]/div[2]/input')
    EDIT_NYCT_START_DATE =(By.XPATH, '//*[@id="NYCT_amend_start_end"]/div[1]/input')
    EDIT_NYCT_EXP_DATE =(By.XPATH, '//*[@id="NYCT_amend_start_end"]/div[2]/input')
    EDIT_SERVICE_AGREE_START_DATE =(By.XPATH, '//*[@id="service_agree_start_end"]/div[1]/input')
    EDIT_SERVICE_AGREE_EXP_DATE =(By.XPATH, '//*[@id="service_agree_start_end"]/div[2]/input')
    EDIT_WELLCARE_START_DATE =(By.XPATH, '//*[@id="wellcare_ins_amend_start_end"]/div[1]/input')
    EDIT_WELLCARE_EXP_DATE =(By.XPATH, '//*[@id="wellcare_ins_amend_start_end"]/div[2]/input')
    EDIT_VISIT_DATE =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[12]/div/div[1]/input')
    EDIT_VISIT_PERFORMD =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[12]/div/div[2]/input')
    EDIT_VISIT_TYPE =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[12]/div/div[3]/input')
    EDIT_APP_CANCELLED =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[12]/div/div[4]/select')
    EDIT_NO_SHOW =(By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[12]/div/div[5]/select')
    EDIT_PROVIDER_AUDIT_START_DATE =(By.XPATH, '//*[@id="provider_audit_start_end"]/div[1]/input')
    EDIT_PROVIDER_AUDIT_EXP_DATE =(By.XPATH, '//*[@id="provider_audit_start_end"]/div[2]/input')
    BASE_SUBMIT = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[3]/form/div[13]/span/button')


class DispatchingPageLocators(object):
    SHOW_ALL_BOOKING = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[1]/a/uib-tab-heading/span')
    ADD_A_NEW_BOOKING = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[2]/a/uib-tab-heading/span')
    SCHEDULED_TRIP = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[3]/a/uib-tab-heading/span')
    SEARCH_DROPBING = (By.XPATH, '//*[@id="admin-table-searching-column-name-selection"]')
    SEARCH_BOX = (By.XPATH, '//*[@id="admin-table-search"]')
    SEARCH_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/dispatching-tab-data-table/div[1]/div[1]/div[3]/button')
    TABLE_TRIP_ID = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Trip ID")])[1]')
    TABLE_TS = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "TS")])[1]')
    TABLE_RS = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "RS")])[1]')
    TABLE_AGEBCY_NAME = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Agency Name")])[1]')
    TABLE_INSURANCE_ID = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Insurance ID")])[1]')
    TABLE_PICKUP_DATE = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Pickup Date")])[1]')
    TABLE_PASSENGER_NAME = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Passenger Name")])[1]')
    TABLE_PASSENGER_PHONE = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Passenger Phone")])[1]')
    TABLE_PASSENGER_EMAIL = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Passenger Email")])[1]')
    TABLE_WHEELCHAIR = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Wheelchair")])[1]')
    TABLE_PICKUP_LOCATION = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Pickup Location")])[1]')
    TABLE_DESTINATION_LOCATION = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Destination location")])[1]')
    TABLE_VEHICLE_TYPE = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Vehicle Type")])[1]')
    TABLE_COMMENTS = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Comments")])[1]')
    TABLE_DRIVER = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Driver")])[1]')
    TABLE_ASSIGNED_DRIVER = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Assigned Driver")])[1]')
    TABLE_CREATED_TIME = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th[contains(text(), "Created Time")])[1]')
    ACTION_EDIT_FOR_1ST_DISPATCH = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//td/span/i)[1]')
    ACTION_DELETE_FOR_1ST_DISPATCH = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//td/span/i)[2]')
    EDIT_COMPANY_NAME = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[1]/div[2]/select')
    EDIT_BASE_NAME = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[1]/div[3]/select')
    EDIT_FIRST_NAME_DROPDOWN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[2]/div/div[1]/span')
    EDIT_FIRST_NAME_BOX = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[2]/div/input[1]')
    EDIT_LAST_NAME = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[3]/input')
    EDIT_PHONE_NUMBER = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[1]/div[4]/input')
    EDIT_TRIP_TYPE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[2]/select')
    EDIT_ONE_WAY_BTN = (By.XPATH, '//*[@id="route_option_1"]')
    EDIT_ROUND_TRIP_BTN = (By.XPATH, '//*[@id="route_option_2"]')
    DISPATCH_SUBMIT_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[4]/span/button')
    EDIT_DRIVER = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[2]/div[3]/select')
    EDIT_DRIVER_MANUALLY = (By.XPATH, '//*[@id="driver_option_1"]')
    EDIT_DRIVER_AUTO = (By.XPATH, '//*[@id="driver_option_2"]')
    EDIT_PICKUP_TIME = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[6]/div[1]/input')
    EDIT_RETURN_TIME = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[6]/div[2]/input')
    EDIT_PICKUP_LOCATION = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[6]/div[3]/input')
    EDIT_DESTINATION_LOCATION = (By.XPATH, '//*[@id="destinationLocation"]')
    EDIT_VEHICLE_TYPE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[6]/div[5]/select')
    EDIT_INSURANCE_ID = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[6]/div[5]/input')
    EDIT_INSURANCE_ID2 = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[6]/div[7]/input')
    EDIT_AGENCY_NAME = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[6]/div[6]/select')
    EDIT_FARE_TYPE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[6]/div[6]/div[2]/select')
    EDIT_ESTIMATED_FARE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[6]/div[6]/div[3]/input')
    EDIT_DISPATCH_IMM = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/div[2]/div[6]/div[2]/div[1]/label/input')


class ContentPageLocators(object):
    SHOW_ALL_CONTENT = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[1]/a/uib-tab-heading/span')
    ADD_A_NEW_CONTENT = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div/div/ul/li[2]/a/uib-tab-heading/span')
    TABLE_STATUS = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Status")])[1]')
    TABLE_BASENAME = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Base Name")])[1]')
    TABLE_TITLE = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Title")])[1]')
    TABLE_DATE =  (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//th/span[contains(text(), "Date")])[1]')
    ACTION_EDIT_FOR_1ST_CONTENT = (By.XPATH, '(//table[@class="admin-tab-data-table-table display cell-border dataTable"]//td/i)[2]')
    EDIT_BASE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[2]/div/select')
    EDIT_TITLE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[3]/div[1]/input')
    EDIT_DESCRIPTION = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[3]/div[2]/div/div[2]')
    EDIT_DESCRIPTION_INPUT = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[3]/div[2]/div/input')
    EDIT_PAGE_TITLE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[4]/div[1]/input')
    EDIT_PAGE_KEYWORDS = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[4]/div[2]/input')
    EDIT_STATUS_ACTIVE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[4]/div[3]/input[1]')
    EDIT_STATUS_INACTIVE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[1]/div[4]/div[3]/input[2]')
    SUBMIT_BUTTON = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/div[2]/form/div[2]/span/button')

class FlightCheckPageLocators(object):
    AIRLINE = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/flight-check-tab-data-table/form/div[1]/div/input')
    FLIGHT_NUMBER = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/flight-check-tab-data-table/form/div[2]/div/input')
    DEPARTING_DATE = (By.XPATH, '//*[@id="depart-date"]')
    SEARCH_BTN = (By.XPATH, '//*[@id="main-content-container-wrappper"]/div/div/div/div/flight-check-tab-data-table/form/span')